### PR TITLE
External Credentials Manager in terra-env

### PR DESCRIPTION
**Pull request by dvoet**

### CODE REVIEW

**Review by choover-broad — COMMENTED** [review]
Hi @dvoet, thanks for the PR!

A few preliminary comments:
* We're trying to avoid adding new applications to the terra-env module and instead run them in their own Atlantis project. This is to (1) reduce contention around Atlantis PR locks and Terraform state locks across teams and (2) avoid a giant state file that takes several minutes to preview and apply. See the [sam deployment here](https://github.com/broadinstitute/terraform-ap-deployments/tree/master/sam) as an example.

* Could you pick a short, single-word name for this new service so it can be referred to consistently in infrastructure? See DevOps [recommendations](https://github.com/broadinstitute/terra-helmfile/blob/master/docs/NAMING.md#applications) and [FAQ](https://github.com/broadinstitute/terra-helmfile/blob/master/docs/NAMING.md#faq) as well as guidelines from [Platform Foundations](https://docs.google.com/document/d/1yvVlQnXDKOKSKEKIsMrWNh0LfwLuI7FWt57sa43d7Qg/edit?usp=sharing)

**Comment by dvoet** [comment]
> Hi @dvoet, thanks for the PR!
> 
> A few preliminary comments:
> 
> * We're trying to avoid adding new applications to the terra-env module and instead run them in their own Atlantis project. This is to (1) reduce contention around Atlantis PR locks and Terraform state locks across teams and (2) avoid a giant state file that takes several minutes to preview and apply. See the [sam deployment here](https://github.com/broadinstitute/terraform-ap-deployments/tree/master/sam) as an example.
> * Could you pick a short, single-word name for this new service so it can be referred to consistently in infrastructure? See DevOps [recommendations](https://github.com/broadinstitute/terra-helmfile/blob/master/docs/NAMING.md#applications) and [FAQ](https://github.com/broadinstitute/terra-helmfile/blob/master/docs/NAMING.md#faq) as well as guidelines from [Platform Foundations](https://docs.google.com/document/d/1yvVlQnXDKOKSKEKIsMrWNh0LfwLuI7FWt57sa43d7Qg/edit?usp=sharing)

on the second bullet - the name is externalcreds or External Credentials Manager or ECM following the naming doc, I believe I have been consistent in various usages and followed the pattern set by workspace manager.

**Comment by choover-broad** [comment]
> on the second bullet - the name is externalcreds or External Credentials Manager or ECM following the naming doc, I believe I have been consistent in various usages and followed the pattern set by workspace manager.

Workspace Manager is kind of an anti-pattern. The Helm chart is called `workspacemanager`, the Terraform module is called `terra-workspace-manager`, the Ingress hostname is `workspace` because FQDNs with `workspacemanager` were too long to fit in a LetsEncrypt Cert in some environments...

Contrast with `leonardo`, `buffer`, or `janitor`... Short, sweet and no need to switch between camel case, underscores, and dashes depending on the context. When it comes to infrastructure-as-code, I'll take a name like `kong` over an ambiguously-abbreviated compound name like `externalcreds` any day.

Our team did try to push back on `Workspace Manager` as a service name when it first launched and we lost. :) Of course you can choose to disregard this plea as well.

**Comment by dvoet** [comment]
> When it comes to infrastructure-as-code, I'll take a name like kong over an ambiguously-abbreviated compound name like externalcreds any day.

I think you will lose again, sorry. Externalcreds is the agreed upon short name given the naming doc. It may be ambiguous but we have to have a meaningful name

**Comment by choover-broad** [comment]
> I think you will lose again, sorry. Externalcreds is the agreed upon short name given the naming doc. It may be ambiguous but we have to have a meaningful name

That's fine, can we agree to use `externalcreds` consistently in infrastructure-as-code representations? I.e.
 the Helm chart and Terraform modules and ArgoCD deployment and service DNS will all be `externalcreds`

**Pull request merged**
